### PR TITLE
Support for admin popup windows

### PR DESCRIPTION
**Pull request by bashu**

### CODE REVIEW

**Comment by bashu** [comment]
@jsocol can you check this?

**Comment by jsocol** [comment]
I haven't had a problem with pop-ups and adminplus. Can you give a little more details about what the problem is? Affected Django versions? Maybe a screenshot of the unpatched and patched versions?

**Comment by bashu** [comment]
this patch hides breadcrumb when ``is_popup`` is ``True``, lick it's done in django, see https://github.com/django/django/blob/master/django/contrib/admin/templates/admin/base.html#L20-L60

**Comment by jsocol** [comment]
I'd love to see a screenshot of the change, because in that template, the entire `breadcrumb` block is _already_ inside a `if not_popup` block: https://github.com/django/django/blob/master/django/contrib/admin/templates/admin/base.html#L54-L59

**Pull request closed without merging**
