### PR TITLE
Get tests running on Django 2

### PR DESCRIPTION
**Pull request by jsocol**

### CODE REVIEW

**Comment by pcraciunoiu** [comment]
Hey @jsocol, long time :)

A project I help maintain is looking to upgrade from Django 1 to 2 and uses this to add 3 custom pages to the admin. Looks like this branch is the best we've got to stick with this project, and I'm not sure how well it would work?

Alternatively, I was doing some research, stumbled upon [this SO answer](https://stackoverflow.com/a/56476261), but `django-admin-tools` does seem heavy for just this one use case. Are you aware of any good alternatives? What would you suggest?

**Comment by jsocol** [comment]
Hey @pcraciunoiu!

This was difficult at the time because various 2.x versions of Django were doing very different things within the admin, and supporting them all was maybe impossible. I haven't taken a look recently, but since 2.0 and 2.1 are no longer supported, and we only need 1.11, 2.2, and 3.0, the situation might have changed. I'd also be happy to drop 1.11 and only support 2.2 and 3, if it makes things significantly easier. (And we could drop Py2 entirely at that point.)

So I'm super happy to look at PRs that help get to a place where 2.2 and 3.0 are supported. Unfortunately I don't have time to do the work right now, but I'd love if this got to a useful place again, and would happily shepherd along code.

Alternatively, if you're interested, I'd be willing to give you commit here and share some maintenance burden ;)

**Comment by mbaechtold** [comment]
As of today, only 2.2, 3.0 and 3.1 are supported (see https://www.djangoproject.com/download/). And official support for Python 2.x has been dropped a few months ago. I suggest this useful package does the same 😉

**Comment by jsocol** [comment]
Hi @mbaechtold, I agree! There were a lot of changes to the admin system between 1.11 and 2.2, and there is going to be some work needed to make that happen. My comment above still holds true, I don’t have the bandwidth to do the investigation to figure out the changes needed, but I’m very happy to look at PRs that help support those versions.

**Comment by jsocol** [comment]
This is so far out of date at this point :shame:

**Pull request closed without merging**
